version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: "gitsubmodule"
    directory: "/thirdparty"
    schedule:
      interval: "weekly"
      day: "friday"