name: ensure-formatting

on:
  pull_request:

jobs:
  ensure-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Test formatting for all files
        working-directory: ${{ github.workspace }}
        run: |
          export CLANG_FORMAT_BIN='clang-format-15'
          ./scripts/check-format.sh